/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.hasithaa.diagram;

import io.ballerina.compiler.syntax.tree.SyntaxKind;
import io.ballerina.projects.plugins.CodeAnalysisContext;
import io.ballerina.projects.plugins.CompilerPlugin;
import io.ballerina.projects.plugins.CompilerPluginContext;

import java.util.ArrayList;

public class DiagramCompilerPlugin extends CompilerPlugin {

    @Override
    public void init(CompilerPluginContext ctx) {

        ctx.addCodeAnalyzer(new DiagramAnalyzer());
    }

    static class DiagramAnalyzer extends io.ballerina.projects.plugins.CodeAnalyzer {

        @Override
        public void init(CodeAnalysisContext ctx) {
            ArrayList<SyntaxKind> syntaxKinds = new ArrayList<>();
            syntaxKinds.add(SyntaxKind.FUNCTION_DEFINITION);
            ctx.addSyntaxNodeAnalysisTask(new CodeAnalyzer<>(), syntaxKinds);
        }
    }
}
